### ISSUE TITLE
Getting authorization failed messages in Homebridge Logs

### ISSUE THREAD

**Issue by bcullman** [n0rt0nthec4t/homebridge-nest-accfactory#83]
I am seeing the following messages constantly scrolling in my homebridge log:

```
[3/11/2025, 3:02:40 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:02:40 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
[3/11/2025, 3:02:55 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:02:55 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
[3/11/2025, 3:03:10 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:03:10 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
[3/11/2025, 3:03:25 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:03:25 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
[3/11/2025, 3:03:40 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:03:40 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
etc...
```

I believe I followed the directions for setting up a nest account, and a goggle account correctly. Plus, both my nest thermostat and nest camera appear to be working properly.

after trying to get a fresh one, and restarting the plugin, i see this:

```
[3/11/2025, 3:09:41 PM] [homebridge-nest-accfactory] Process Ended. Code: 143, Signal: null
[3/11/2025, 3:09:48 PM] [homebridge-nest-accfactory] Restarting Process...
[3/11/2025, 3:09:51 PM] [homebridge-nest-accfactory] Launched child bridge with PID 382534
[3/11/2025, 3:09:54 PM] Registering platform 'homebridge-nest-accfactory.NestAccfactory'
[3/11/2025, 3:09:54 PM] [homebridge-nest-accfactory] Loaded homebridge-nest-accfactory v0.2.5 child bridge successfully
[3/11/2025, 3:09:54 PM] Loaded 2 cached accessories from cachedAccessories.0E4627275816.
[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Specified ffmpeg binary "/var/lib/homebridge/ffmpeg" was not found
[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Stream video/recording from camera/doorbells will be unavailable
[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Loading accessory from cache: Downstairs
[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Loading accessory from cache: Front Door
[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Performing Google account authorisation 
[3/11/2025, 3:09:55 PM] Homebridge v1.9.0 (HAP v0.12.3) (homebridge-nest-accfactory 8774) is running on port 56349.
[3/11/2025, 3:09:55 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[3/11/2025, 3:09:55 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
[3/11/2025, 3:09:58 PM] [homebridge-nest-accfactory] Successfully authorised using Google account
[3/11/2025, 3:10:01 PM] [homebridge-nest-accfactory] Setup Nest Doorbell (wired) as "Front Door"
[3/11/2025, 3:10:01 PM] [homebridge-nest-accfactory]   += EveHome support as "motion"
[3/11/2025, 3:10:01 PM] [homebridge-nest-accfactory] Setup Nest Learning Thermostat (3rd gen) as "Downstairs"
[3/11/2025, 3:10:01 PM] [homebridge-nest-accfactory]   += EveHome support as "thermo"
[3/11/2025, 3:10:10 PM] [homebridge-nest-accfactory] Performing Nest account authorisation 
[3/11/2025, 3:10:10 PM] [homebridge-nest-accfactory] Authorisation failed using Nest account
...same loop as above
```

Unsure if i am missing out on features, or if I can remove the Nest login stuff so i stop seeing errors in the log

**Comment by n0rt0nthec4t** [comment]
Thanks for taking the time to raise your issue.

Do you need to use Both a Nest account and Google account at the same time? That login do you use for the Nest app?

**Comment by bcullman** [comment]
@n0rt0nthec4t 

> Do you need to use Both a Nest account and Google account at the same time? 

that was sorta my question here... both the Nest thermostat I have and the Nest Video doorbell i have seem to be working in HomeKit just fine. 

I do have both a Nest and a google account. Does this mean i don't need to provide both in the config? this was not clear to me.

**Comment by n0rt0nthec4t** [comment]
In your case, use the Google account for login as long as if presents all your devices. There is the scope by using both to use two different accounts ie: different homes to add devices

You'll also need to fix up path to ffmpeg binary for the doorbell. I really should fix the code and make it look where the homebridge docker instance has it

**Comment by n0rt0nthec4t** [comment]
Try clear the Home bridge accessories cache?

**Comment by bcullman** [comment]
@n0rt0nthec4t 

> Try clear the Home bridge accessories cache?

tried that, but still get the event log error above. Does it just mean by camera does not support secure video?

**Comment by n0rt0nthec4t** [comment]
Nom its should work with HKSV. I'll have to look into it work out why failing for you. Maybe have a theory do with the accessories already under HomeKit and switching from non-hksv to hksv. Will try that scenario 

Maybe you can completely remove the plugin, ensure no cached accessories remaining from my plugin in HomeBridge and redo from scratch ?

**Comment by bcullman** [comment]
@n0rt0nthec4t 

just did a completed uninstall and reinstall. same error.

**Comment by n0rt0nthec4t** [comment]
ok. .can you ping me via email link in bio. Like to work offline with you to resolve. Its like there are two nest doorbells in HomeKit (or homebridge) with hksv

**Comment by bcullman** [comment]
thanks to @n0rt0nthec4t for working with me offline to sort this out

I _think the issue is that when i intially set up the plugin, i did not have HKSV enabled. i later enabled it, and thats when i began getting HKSV log errors. 

My issue was resolved by (while HKSV was still checked) going to settings, choosing "remove individual accessories", selecting the nest-accfactory bridge, and removing only my existing front door accessory. after restarting, it recreated the front door accessory, which was created from the start with HKSV enabled. it then claimed it was enabled, no log errors

**Comment by DigitalFokus** [comment]
Sure thing. I've set debug in Homebridge and after HB restart, it looks like the prior token had a "USER_LOGGED_OUT" response returned:

[8/10/2025, 9:24:19 PM] [NestAccfactory] Performing authorisation for connection "google" 
[8/10/2025, 9:24:19 PM] [NestAccfactory] OAuth reponse object { error: 'USER_LOGGED_OUT', detail: 'No active session found.' }
[8/10/2025, 9:24:19 PM] [NestAccfactory] Failed to connect using Google credentials for connection "google": Missing access_token in OAuth response
[8/10/2025, 9:24:19 PM] [NestAccfactory] Authorisation failed using Google account for connection "google"

I've set a new token again via incognito window and close the incognito window out without logout again. It's holding right now but I'll report back once it starts failing again to see if I get anything extra between the success to failure.

**Comment by DigitalFokus** [comment]
After redoing the token/cookie last night with debug on, I see the same where there were a few successful refreshes and then it's randomly logged out:

[8/10/2025, 9:28:24 PM] [NestAccfactory] Loaded protobuf support files for Google API
[8/10/2025, 9:28:24 PM] [NestAccfactory] Performing authorisation for connection "google" 
[8/10/2025, 9:28:26 PM] [NestAccfactory] Successfully authorised using Google account for connection "google"
[8/10/2025, 9:28:26 PM] [NestAccfactory] Starting Nest API subscribe for connection "google"
[8/10/2025, 9:28:26 PM] [NestAccfactory] Starting Google API observe for connection "google"
...
[8/10/2025, 10:23:25 PM] [NestAccfactory] Performing periodic token refresh using Google account for connection "google"
[8/10/2025, 10:23:27 PM] [NestAccfactory] Successfully performed token refesh using Google account for connection "google"
[8/10/2025, 10:24:31 PM] [NestAccfactory] Access token has changed for uuid "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX". Updating token
[8/10/2025, 11:18:26 PM] [NestAccfactory] Performing periodic token refresh using Google account for connection "google"
[8/10/2025, 11:18:28 PM] [NestAccfactory] Successfully performed token refesh using Google account for connection "google"
[8/10/2025, 11:19:59 PM] [NestAccfactory] Access token has changed for uuid "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX". Updating token
[8/11/2025, 12:13:27 AM] [NestAccfactory] Performing periodic token refresh using Google account for connection "google"
[8/11/2025, 12:13:27 AM] [NestAccfactory] OAuth reponse object { error: 'USER_LOGGED_OUT', detail: 'No active session found.' }
[8/11/2025, 12:13:27 AM] [NestAccfactory] Failed to connect using Google credentials for connection "google": Missing access_token in OAuth response
[8/11/2025, 12:13:27 AM] [NestAccfactory] Token refresh failed using Google account for connection "google"

**Comment by DigitalFokus** [comment]
I managed to fix this by using a different cookie than the noted "last iframe" in the documentation. Using the cookie from the entry directly above the last iframe entry has held just fine with no logout or issues.

**Comment by n0rt0nthec4t** [comment]
OK.. Maybe we need to keep this in mind and potentially revise the instructions
